# Generated by Django 4.1.2 on 2022-11-02 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_url',
            new_name='url',
        ),
    ]
