# Generated by Django 4.1.2 on 2022-11-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_order_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='products',
            field=models.ManyToManyField(blank=True, to='cart.productitem'),
        ),
    ]
