# Generated by Django 4.1.2 on 2022-11-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_order_products'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='orders',
        ),
        migrations.AddField(
            model_name='shopuser',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='shopuser', to='cart.order'),
        ),
    ]
