# Generated by Django 4.1.2 on 2022-11-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_shopuser_orders_shopuser_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='is_moderator',
        ),
    ]
